theme: minima
  skin: solarized

defaults:
  -
    scope:
      path: ""  # all files in project
    values:
      layout: default

author:
  name: C.J. May
  email: winbin.wtf@cjmay.info

minima:
  social_links:
    github: lawndoc
    twitter: lawndoc
    linkedin: cj-may

plugins:
 - jekyll-seo-tag
