remote_theme: jekyll/minima

defaults:
  -
    scope:
      path: ""  # all files in project
    values:
      layout: page

author:
  name: C.J. May
  email: winbin.wtf@cjmay.info

minima:
  skin: solarized
  social_links:
    github: lawndoc
    twitter: lawndoc
    linkedin: cj-may

plugins:
 - jekyll-seo-tag
 - jekyll-remote-theme
