remote_theme: jekyll/minima

defaults:
  -
    scope:
      path: ""  # all files in project
    values:
      layout: page

author:
  name: C.J. May
  email: winbin.wtf@cjmay.info

minima:
  skin: solarized
  social_links:
    - {platform: github, user_url: "https://github.com/lawndoc"}
    - {platform: twitter, user_url: "https://twitter.com/lawndoc"}
    - {platform: linkedin, user_url: "https://linkedin.com/in/cj-may"}

plugins:
 - jekyll-seo-tag
 - jekyll-remote-theme
