name: External Jekyll Build

on:
  pull_request:
    branches:
    - '*'
  workflow_dispatch:

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Ruby installation
      uses: ruby/setup-ruby@v1
      with:
        working-directory: ./docs/
        ruby-version: 3.1.2
        bundler-cache: true
    - name: Compile Jekyll
      run: |
        cd docs
        bundle exec jekyll build --future --verbose
  
  build-windows:

    runs-on: windows-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@v3
    - name: Ruby installation
      uses: ruby/setup-ruby@v1
      with:
        working-directory: ./docs/
        ruby-version: 3.1.2
        bundler-cache: true
    - name: Compile Jekyll
      run: |
        cd docs
        bundle exec jekyll build --future --verbose
