name: External Jekyll Build

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
    - '*'

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container (Ubuntu)
      run: |
        docker run \
        -v ${{ github.workspace }}/docs/ -v ${{ github.workspace }}/docs/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /docs/ && jekyll build --future"
  
  build-windows:

    runs-on: windows-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@v3
    - name: Ruby installation
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Compile Jekyll
      run: |
        cd docs
        bundle exec jekyll serve
